### ISSUE TITLE
Cannot find module 'xmldom'

### ISSUE THREAD

**Issue by kyleherzog** [MrTarantula/ProjectVersionTools#7]
Since being upgraded to version 1.2, we are now getting an error saying that it cannot find module 'xmldom'. Up until today we were using v1.0 of this task and it worked fine.  Her are the log details:

2018-11-12T16:49:50.2996229Z ==============================================================================
2018-11-12T16:49:50.2996430Z Task         : Get Application Version As Variables
2018-11-12T16:49:50.2996783Z Description  : Read the Application Version from a project file and use as build variables.
2018-11-12T16:49:50.2996949Z Version      : 1.2.0
2018-11-12T16:49:50.2997075Z Author       : Ryan Tauriainen
2018-11-12T16:49:50.2997226Z Help         : [More Information](https://github.com/MrTarantula/ProjectVersionTools)
2018-11-12T16:49:50.2997416Z ==============================================================================
2018-11-12T16:49:50.4312852Z module.js:471
2018-11-12T16:49:50.4313303Z     throw err;
2018-11-12T16:49:50.4313834Z     ^
2018-11-12T16:49:50.4313914Z 
2018-11-12T16:49:50.4314031Z Error: Cannot find module 'xmldom'
2018-11-12T16:49:50.4314232Z     at Function.Module._resolveFilename (module.js:469:15)
2018-11-12T16:49:50.4314456Z     at Function.Module._load (module.js:417:25)
2018-11-12T16:49:50.4314748Z     at Module.require (module.js:497:17)
2018-11-12T16:49:50.4314938Z     at require (internal/module.js:20:19)
2018-11-12T16:49:50.4315203Z     at Object.<anonymous> (C:\agent2\_work\_tasks\versionintovariables_39b7bb29-595d-44df-8881-217649005ccd\1.2.0\versionintovariables.js:12:16)
2018-11-12T16:49:50.4315397Z     at Module._compile (module.js:570:32)
2018-11-12T16:49:50.4315575Z     at Object.Module._extensions..js (module.js:579:10)
2018-11-12T16:49:50.4315738Z     at Module.load (module.js:487:32)
2018-11-12T16:49:50.4315905Z     at tryModuleLoad (module.js:446:12)
2018-11-12T16:49:50.4316064Z     at Function.Module._load (module.js:438:3)
2018-11-12T16:49:50.4394556Z ##[error]Exit code 1 returned from process: file name 'C:\agent2\externals\node\bin\node.exe', arguments '"C:\agent2\_work\_tasks\versionintovariables_39b7bb29-595d-44df-8881-217649005ccd\1.2.0\versionintovariables.js"'.

**Comment by MrTarantula** [comment]
Apologies. This worked by chance up until now because I did not have xmldom in `package.json` for this task. It should be fixed in v1.2.1.

**Comment by MrTarantula** [comment]
Can you confirm that it is working now?

**Comment by kyleherzog** [comment]
Fix confirmed. Thanks!
